from telegram import Update, ReplyKeyboardMarkup
from telegram.ext import Application, CommandHandler, MessageHandler, ContextTypes, filters
import os
import random
import json
from datetime import datetime

TOKEN = os.getenv("TELEGRAM_TOKEN")

CARDS_FOLDER = "memes"
DATA_FILE = "users_data.json"

COOLDOWN_HOURS = 12
